language: python
python:
    "3.8"
git:
    depth: 2
    submodule: True

env:
    - name=struct.cpp
    - fullname=*.cpp
    - job="update
    global:
        - name=struct.cpp
        - name=
        - name=*.cpp

before_install:
    - if [ $job=="update" ];then apt update; fi
install:
    - if [ -e $name ];then apt install python3-dev, libboost-python1.67-dev;fi
script:
    - echo using $name
    - if [ -e $name ];then exit; else bash make $name;fi
      
after_script:
    echo installed with $?

